# Generated by Django 5.2.1 on 2025-05-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huissier',
            old_name='card_id',
            new_name='npi',
        ),
        migrations.AlterField(
            model_name='huissier',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='huissiers/'),
        ),
    ]
