# Generated by Django 5.2.1 on 2025-05-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_rename_card_id_huissier_npi_alter_huissier_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='huissier',
            name='phone',
            field=models.CharField(default='00000', max_length=200, verbose_name='Numéro de téléphone'),
        ),
    ]
