# Generated by Django 5.2.1 on 2025-05-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_huissier_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financial',
            old_name='card_id',
            new_name='npi',
        ),
        migrations.AddField(
            model_name='financial',
            name='phone',
            field=models.CharField(default='00000', max_length=100),
        ),
        migrations.AlterField(
            model_name='financial',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='financials/'),
        ),
    ]
