# Generated by Django 5.2.1 on 2025-05-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_alter_huissier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='huissier',
            name='zone',
            field=models.CharField(default='', max_length=500, verbose_name='Zone de front office'),
        ),
    ]
