# Generated by Django 5.2.1 on 2025-05-27 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_huissier_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('localisation', models.CharField(max_length=600, verbose_name='localisation de zone')),
                ('front_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.frontoffice')),
            ],
        ),
    ]
