# Generated by Django 5.2.1 on 2025-05-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_availablezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontoffice',
            name='localisation',
        ),
    ]
