# Generated by Django 5.2.1 on 2025-06-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_remove_frontoffice_localisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Pays', 'verbose_name_plural': 'Pays'},
        ),
    ]
