# Generated by Django 5.2.1 on 2025-06-04 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0009_alter_country_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availablezone',
            name='localisation',
        ),
    ]
