# Generated by Django 5.2.1 on 2025-06-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
