# Generated by Django 5.2.1 on 2025-06-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_loan_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
