# Generated by Django 5.2.1 on 2025-06-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_loan_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='rate',
        ),
    ]
