# Generated by Django 5.2.1 on 2025-07-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_loan_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='creditor_npi',
            field=models.CharField(null=True, verbose_name='NPI du créancier'),
        ),
    ]
