# Generated by Django 5.2.1 on 2025-05-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_scoreuser_cree_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreuser',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
